### PR TITLE
setup a stable and latest build in travis ci

### LINKED ISSUE #17: Use specific versions for package depedencies
It looks that we are currently running tests using the latest master version of the simphony-commons library. As a result due to frequent changes (some of the not backwards compatible) that take place in the simphony-commons library will cause the test builds to fail, which make developement a litle more complicated.

To counter the effects of a fast paced development in simphony-common a common pattern is to 
- First always use a fixed version for the depedencies in requirements files so that there is always control on what we are testing again.
- Setup a second build configuration that will run tests against the latest master version of simphony-commons to see possible issues if we had upgraded to the latest version but does not cause the travis-ci check to failure.

@khiltunen, if it ok with you, I can update the travis-yml configuration with the above pattern. It would be a good example to the other simphony collaborators on how to use travis-ci to better manage depedenvy issues with new versions of simphony-common

### PR DESCRIPTION
**Pull request by itziakos**
This PR fixes #17. We setup two builds in travis-ci one working on the latest stable release of simphony-common that openfoam master supports and the other on the latest master version of simphony-common. The cutting edge build failure or success will not affect the commit status on PRs but will provide a preview on what currently breaks and will need to be fixed in order to use the latest simphony-common code.

### CODE REVIEW

**Comment by itziakos** [comment]
@khiltunen, This PR  is ready for review. 

We setups two builds on travis-ci for every change that is pushed to github. The first build is against a stable version of simphony-common (currently 0.1.2) and the second build is for then latest master commit of simphony-common. The seconds build is designated as a build that can fail

This setup will help when you are adding features in the openfoam-simphony wrapper. By selecting a specific simphony version for testing to avoid the false positives that are due to recent changes in simphony common. Thus the PR can be reviewed tested and merged without problems. 

At the same time by having the cutting edge built at the same time you can check to see what breaks with the new version of simphony and thus make a separate PR making the necessary changes.

As a result you separate the concepts of writing code to add a feature ro fix a bug in simphony-opefoam and writing code to support a new version of simhony.

**Comment by itziakos** [comment]
@khiltunen  is this ok to merge?

**Comment by khiltunen** [comment]
Yes.

**Comment by itziakos** [comment]
ok, I will update the branch to let travis-ci run one more time and then merge. 

Thanks

**Comment by itziakos** [comment]
@khiltunen, I think that his PR might conflict with #23, so I think that it is better if we revisit this after #23 is merged

**Comment by khiltunen** [comment]
Your are right. Let's wait for the #23.

**Comment by stefanoborini** [comment]
Closing as it's no longer relevant.

**Pull request closed without merging**
