### PR TITLE
Version 0.2.0

### PR DESCRIPTION
**Pull request by khiltunen**
This PR sets OpenFOam wrapper version to 0.2.0

### CODE REVIEW

**Comment by khiltunen** [comment]
@TobiasRasp i've changed the version number to 0.2.0. OK to merge ?

**Comment by TobiasRasp** [comment]
Yes!

**Comment by nathanfranklin** [comment]
@khiltunen , Are there any other version numbers that need to be updated?  I suspect the recent changes require at least version of  `simphonyfoaminterface` to be updated.

**Comment by khiltunen** [comment]
Yes you're right. It's now updated.

**Comment by khiltunen** [comment]
Any objections to merge ?

**Comment by TobiasRasp** [comment]
No, not from my side

**Pull request merged**
