### PR TITLE
WIP: Feature pyFoam numerola

### PR DESCRIPTION
**Pull request by khiltunen**
I included pyFoam installation script. It needs sudo rights to work. Should we have installation for regular users ?

### CODE REVIEW

**Comment by itziakos** [comment]
@khiltunen, it looks that PyFoam is not properly installed since the Foam module cannot be imported (see https://travis-ci.org/simphony/simphony-openfoam/builds/49742327). There is a https://github.com/jstasiak/travis-solo package that should allow running the travis-ci file on a local machine. This should help debugging the problem.

By the way, why did you change the installation to user?

**Comment by khiltunen** [comment]
Just get the impression from the Foam installation skript that the installation should be per user. I think that the pyFoam installation script should work for sudo installing just taking --user option away. I've just installed OpenFoam 2.3.0 to Ubuntu 14.04. I put the corresponding installation script to setup-travis-ci branch. That is also for regular user. I try to use that travis-solo.

**Comment by itziakos** [comment]
@khiltunen, I think I have found the problem, we did not setup the openfoam enviroment. I have updated the script and at least PyFoam should be working now. Sorry it took longer than expected, I had to setup a clean ubutnu 10.24 VM.

**Comment by itziakos** [comment]
> Just get the impression from the Foam installation skript that the installation should be per user. I think that the pyFoam installation script should work for sudo installing just taking --user option away.

For travis-ci we run the installation script with sudo so it should be ok.

**Comment by itziakos** [comment]
@khiltunen, installation of PyFoam works now. Travis-ci fails because of flake8 violations. I also had to add the tests directory to the python packages (there was a missing `__init__.py`) file. I also noticed that you also committed temp files (i.e. files ending in `~`)

**Comment by itziakos** [comment]
@khiltunen, Please note that in ubuntu 12.04 openFOAM 2.2.2 is the latest officially supported. If we need to work with openFOAM we will need to provide a precompiled `deb` files for travis-ci to work.

**Comment by khiltunen** [comment]
If we are going towards Ubuntu 14.04 i think that at that point we should move also to OpenFoam 2.3. Actually we have at a moment only 14.04 on VM, so if dep package is needed for 2.2.x Foam it might be a problem.

**Comment by khiltunen** [comment]
deb packages are available for 2.2.0 which should work for interface codes and pyFoam. Instructions are provided at
http://www.openfoam.org/archive/2.2.0/download/ubuntu.php

**Comment by itziakos** [comment]
> If we are going towards Ubuntu 14.04 i think that at that point we should move also to OpenFoam 2.3. Actually we have at a moment only 14.04 on VM, so if dep package is needed for 2.2.x Foam it might be a problem.

I think that there is a confusion here. Travis-ci is currently using 12.04 were the latest OpenFOAM version available is 2.2.2 (and currently installed by our travis.yml. There is going to be a move to 14.04 later this year but until then we cannot easily have automatic tests on 2.3.0. 

So my suggestion is that for now we use OpenFoam 2.2.2 and move to OpenFOAM 2.3.0 later when the continues automation moves to ubuntu 14.04. 

@khiltunen and @ahashibon does that make sense?

**Comment by itziakos** [comment]
> deb packages are available for 2.2.0 which should work for interface codes and pyFoam. Instructions are provided at http://www.openfoam.org/archive/2.2.0/download/ubuntu.php

we already install OpeFOAM 2.2.2 through deb packages in travis-ci (see log output https://travis-ci.org/simphony/simphony-openfoam/builds/49752710)

**Comment by khiltunen** [comment]
That's right. I thought that was for the 2.1 version. So no problem there.

**Comment by itziakos** [comment]
@khiltunen, I am looking into the plugin setup

**Comment by itziakos** [comment]
@khiltunen, the problem was an incorrect import, I have updated the code and it should work ok now

**Pull request closed without merging**
