### PR TITLE
Fix issue #76

### PR DESCRIPTION
**Pull request by khiltunen**
This PR fixes issue #76 adding contact angle BC to interFoam solver

### CODE REVIEW

**Comment by khiltunen** [comment]
@TobiasRasp could you review the code and test the contact angle BC in your example

**Comment by khiltunen** [comment]
@TobiasRasp flowRate BC is now added and issue to fixedFluxPressure BC fixed. Test and give feedback

**Comment by khiltunen** [comment]
@TobiasRasp is this OK to merge

**Comment by TobiasRasp** [comment]
The dahl-examples work fine now for the foam_controlwrapper, but the foam_internalwrapper still return a Segmentation fault. Except of that, this is ready to merge in my opinion

**Comment by khiltunen** [comment]
Could'nt reproduce the error  on internalwrappers dahl example.

**Pull request merged**
