### PR TITLE
pyFoam installation forced to 0.6.4

### PR DESCRIPTION
**Pull request by khiltunen**
PyFoam installation requires now 0.6.4 version

### CODE REVIEW

**Comment by khiltunen** [comment]
@nathanfranklin could you check that this is OK now

**Comment by nathanfranklin** [comment]
just left a small comment. otherwise, looks good to me :+1:

**Comment by khiltunen** [comment]
Made those suggested changes. OK to merge ?

**Comment by nathanfranklin** [comment]
:+1:

**Pull request merged**
