### PR TITLE
V0.1.3 release

### PR DESCRIPTION
**Pull request by nathanfranklin**

### CODE REVIEW

**Comment by nathanfranklin** [comment]
@norbertonigro @jmarcelogimenez @khiltunen ,  here is the 0.1.3 release.  Please give me the go-ahead to merge this.

simphony-framework can then use this release and we can reactivate the testing in the simphony-framework (simphony/simphony-framework#35) of simphony-openfoam

**Comment by jmarcelogimenez** [comment]
Ok, there are no objections by our side (@norbertonigro, @santiagomarquezd). It remains pending the answer of @khiltunen.
After the merge is done, we will start to work with some of the pending issues.

**Comment by jmarcelogimenez** [comment]
Any news? @khiltunen @nathanfranklin 
Should we wait for merging before to start working?

**Comment by nathanfranklin** [comment]
@jmarcelogimenez ,  this PR should not be delaying any work.  So there is no reason for any development work to wait on it.  Just open a feature branch and begin you work ..(for info:https://publicwiki-01.fraunhofer.de/SimPhoNy-Project/index.php/Simphony_packages_development_workflow#Adding_a_feature
and https://publicwiki-01.fraunhofer.de/SimPhoNy-Project/index.php/Development_guide#Git_Workflow )

**Comment by nathanfranklin** [comment]
>Ok, there are no objections by our side (@norbertonigro, @santiagomarquezd). It remains pending the answer of @khiltunen.

@norbertonigro @jmarcelogimenez @khiltunen, @jamartik ,  if there are no objections, I will merge this PR tomorrow.

**Pull request merged**
